# need 4 gpus

project: coconut
save_path: ./saved_model
name: eli5_coco_1

only_eval: False

coconut: True
cot: False
no_thoughts: False
no_cot: False

c_thought: 1
epochs_per_stage: 3
max_latent_stage: 1
pad_latent_to_max: True

save_only_improve: False
uniform_prob: 0.0
model_id: openai-community/gpt2
load_model_path: None
seed: 42
resume: 0
bf16: False
train_path: /var/local/aurora/TokenSkip/datasets/gsm8k/train.json
val_path: /var/local/aurora/TokenSkip/datasets/gsm8k/test.json
reset_optimizer: False
batch_size_training: 32
debug: False
gradient_accumulation_steps: 1
num_epochs: 5
lr: !!float "1e-4"
weight_decay: 0.01