project: coconut
save_path: ./saved_model
name: eli5_vanilla

# Evaluation mode
only_eval: True

# Disable all special features
coconut: False
cot: False
no_thoughts: True
no_cot: True

c_thought: 0  # No latent thoughts needed
epochs_per_stage: 3
max_latent_stage: 0
pad_latent_to_max: False

save_only_improve: False
uniform_prob: 0.0
model_id: openai-community/gpt2
load_model_path: None  # No finetuned model to load
seed: 42
resume: 0
bf16: False
train_path: /var/local/aurora/TokenSkip/datasets/gsm8k/train.json
val_path: /var/local/aurora/TokenSkip/datasets/gsm8k/test.json
reset_optimizer: False
batch_size_training: 8
debug: False
gradient_accumulation_steps: 1
num_epochs: 1  # Only need one epoch for evaluation
lr: !!float "1e-4"
weight_decay: 0.01